export {
  PTY_CREATE_CANCELLED_MESSAGE,
  PTY_CREATE_CANCELLED_TAG,
  PTY_CREATE_TIMED_OUT_MESSAGE,
  PTY_DISPOSE_TIMED_OUT_MESSAGE,
  TERMINAL_ALREADY_ACTIVE_OR_SHUTTING_DOWN_SUBSTRING
} from "../shared/pty-protocol"
