/**
 * Typed slash-command protocol shared between renderer and main.
 *
 * Design contract:
 *   - The renderer never serialises skill content or path into the user message.
 *     It only sends a typed `SlashInvocation`; main is the sole owner of the
 *     skill body, reading it from disk on-demand.
 *   - `id` is opaque to the renderer — generated by main, echoed back verbatim.
 *     This prevents a compromised renderer from pointing at arbitrary paths.
 *   - Only `kind: "skill"` is implemented today. Other kinds occupy type slots
 *     so downstream dispatchers can switch exhaustively without a fallback that
 *     silently swallows unknown kinds.
 */

/** Unique, stable identifier for a registered slash command. */
export type SlashCommandId = string

/** Invocation payload sent from renderer → main in agent:invoke / agent:resume. */
export type SlashInvocation =
  | { kind: "skill"; id: SlashCommandId; args?: string }
  // Reserved for future kinds (/clear, /model, /hooks, /review).
  // Listed here so dispatch.ts has a non-throwing switch surface ready.
  | { kind: "local"; id: SlashCommandId; args?: string }
  | { kind: "prompt"; id: SlashCommandId; args?: string }
  | { kind: "ui"; id: SlashCommandId; args?: string }

/** Skill-kind command as registered by the registry. */
export interface RegisteredSlashSkill {
  kind: "skill"
  id: SlashCommandId
  name: string
  description: string
  /** Canonical SKILL.md absolute path (source, not enabled-skills copy). */
  skillPath: string
  /** Directory containing SKILL.md — forwarded to the model so resource refs resolve. */
  baseDir: string
  source: "project" | "user" | "plugin"
}

/** Minimal reference — what we attach to the checkpoint + what chips render from. */
export interface SlashSkillRef {
  kind: "skill"
  id: SlashCommandId
  name: string
  source: "project" | "user" | "plugin"
}

/** Fully resolved skill ready to be injected into a model request. */
export interface ResolvedSlashSkill {
  ref: SlashSkillRef
  skillPath: string
  baseDir: string
  /** Raw SKILL.md body — only held in memory during the turn. */
  body: string
  /** Body wrapped in the `<selected_skill_context>` envelope the model sees. */
  renderedContext: string
  /** Heuristic token count for routing context-window guard. */
  estimatedTokens: number
}

/**
 * Per-invocation transient context passed to the runtime middleware.
 * Intentionally decoupled from state.messages so checkpointer never persists the body.
 */
export interface TransientSlashModelContext {
  skill: ResolvedSlashSkill
}

/** Public shape returned to renderer for the slash popover list. */
export interface SlashCommandListItem {
  kind: "skill"
  id: SlashCommandId
  name: string
  description: string
  source: "project" | "user" | "plugin"
}
