import type { CSSProperties } from "react"

export const S: Record<string, CSSProperties> = {
  root:              { display: "flex", flexDirection: "column", height: "100%", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif", background: "#f0efeb" },
  titleBar:          { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 16px", height: 48, background: "#f0efeb", flexShrink: 0 },
  logo:              { width: 28, height: 28, borderRadius: "50%", background: "#cc785c", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 14 },
  titleText:         { fontSize: 15, fontWeight: 500, color: "#1a1a1a" },
  titleActions:      { display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  workspaceBtn:      { display: "inline-flex", alignItems: "center", gap: 6, maxWidth: 240, padding: "6px 10px", fontSize: 12, fontWeight: 600, border: "1px solid #d4d2cc", borderRadius: 8, fontFamily: "inherit", minWidth: 0 },
  workspaceIcon:     { fontSize: 12, lineHeight: 1, color: "inherit", flexShrink: 0 },
  workspaceText:     { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const, minWidth: 0 },
  shareBtn:          { padding: "6px 16px", fontSize: 13, fontWeight: 600, background: "#1a1a1a", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer" },
  mainContent:       { display: "flex", flex: 1, overflow: "hidden" },

  leftPanel:         { width: 420, flexShrink: 0, display: "flex", flexDirection: "column", background: "#ffffff", borderRight: "1px solid #e8e6e0" },
  chatBody:          { flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" },
  emptyState:        { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "32px 24px", flex: 1 },
  emptyTitle:        { fontSize: 22, fontWeight: 600, color: "#1a1a1a", margin: "0 0 8px" },
  emptySubtitle:     { fontSize: 14, color: "#8a8a8a", margin: 0 },
  contextCards:      { display: "flex", flexDirection: "column", gap: 10, width: "100%", maxWidth: 300, marginTop: 24 },
  messageList:       { flex: 1, overflowY: "auto", padding: "16px" },
  inputArea:         { padding: "12px 16px 16px", borderTop: "1px solid #e8e6e0", flexShrink: 0 },
  inputBox:          { border: "1px solid #e0ded8", borderRadius: 12, background: "#fafaf8", padding: "10px 12px" },
  textarea:          { width: "100%", border: "none", background: "transparent", resize: "none", fontSize: 14, color: "#1a1a1a", outline: "none", fontFamily: "inherit", lineHeight: 1.5, boxSizing: "border-box" as const },
  inputToolbar:      { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 8 },
  importBtn:         { padding: "4px 10px", fontSize: 12, fontWeight: 500, background: "none", border: "1px solid #d0cec8", borderRadius: 6, cursor: "pointer", color: "#4a4a4a", fontFamily: "inherit" },
  sendBtn:           { padding: "6px 16px", fontSize: 13, fontWeight: 600, color: "#fff", border: "none", borderRadius: 8, fontFamily: "inherit", transition: "background 0.15s" },
  cancelBtn:         { padding: "6px 16px", fontSize: 13, fontWeight: 600, background: "#e8e6e0", color: "#4a4a4a", border: "none", borderRadius: 8, cursor: "pointer", fontFamily: "inherit" },
  approvalPrimaryBtn: { padding: "6px 12px", fontSize: 12, fontWeight: 700, background: "#1a1a1a", color: "#fff", border: "none", borderRadius: 7, cursor: "pointer", fontFamily: "inherit" },
  approvalSessionBtn: { padding: "6px 12px", fontSize: 12, fontWeight: 600, background: "#2563eb", color: "#fff", border: "none", borderRadius: 7, cursor: "pointer", fontFamily: "inherit" },
  approvalPermanentBtn: { padding: "6px 12px", fontSize: 12, fontWeight: 600, background: "#16a34a", color: "#fff", border: "none", borderRadius: 7, cursor: "pointer", fontFamily: "inherit" },
  approvalRejectBtn: { padding: "6px 12px", fontSize: 12, fontWeight: 600, background: "#ffffff", color: "#4a4a4a", border: "1px solid #d0cec8", borderRadius: 7, cursor: "pointer", fontFamily: "inherit" },

  rightPanel:        { flex: 1, display: "flex", flexDirection: "column", background: "#f0efeb", overflow: "hidden" },
  canvasBar:         { display: "flex", alignItems: "center", padding: "0 12px", height: 45, background: "#f0efeb", borderBottom: "1px solid #e0ded8", flexShrink: 0, gap: 4 },
  navBtn:            { width: 30, height: 30, display: "flex", alignItems: "center", justifyContent: "center", background: "#ffffff", border: "1px solid #d0cec8", borderRadius: 8, cursor: "pointer", fontSize: 14, color: "#4a4a4a", flexShrink: 0 },
  canvasActionBtn:   { display: "flex", alignItems: "center", gap: 6, padding: "5px 12px", fontSize: 13, fontWeight: 500, background: "none", border: "1px solid #d0cec8", borderRadius: 8, cursor: "pointer", color: "#1a1a1a", fontFamily: "inherit" },
  canvas:            { flex: 1, position: "relative" as const, overflow: "hidden" },
  iframe:            { width: "100%", height: "100%", border: "none" },
  canvasEmpty:       { position: "absolute" as const, inset: 0, display: "flex", flexDirection: "column" as const, alignItems: "center", justifyContent: "center", backgroundImage: "radial-gradient(circle, #c8c6c0 1px, transparent 1px)", backgroundSize: "24px 24px" },
  canvasEmptyText:   { fontSize: 18, color: "#8a8a8a", marginBottom: 20, fontWeight: 400 },
  startSketchBtn:    { display: "inline-flex", alignItems: "center", gap: 8, padding: "10px 20px", fontSize: 14, fontWeight: 500, background: "#ffffff", border: "1px solid #d0cec8", borderRadius: 10, cursor: "pointer", color: "#1a1a1a", fontFamily: "inherit", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  generatingRow:     { display: "flex", alignItems: "center", gap: 10 },

  questionsContainer:{ display: "flex", flexDirection: "column" as const, height: "100%", background: "#f5f4f0" },
  questionsInner:    { flex: 1, overflowY: "auto" as const, padding: "40px 48px 24px" },
  questionsTitle:    { fontSize: 26, fontWeight: 600, color: "#1a1a1a", margin: "0 0 32px", lineHeight: 1.2 },
  questionBlock:     { marginBottom: 28 },
  questionLabel:     { display: "block", fontSize: 15, fontWeight: 600, color: "#1a1a1a", marginBottom: 6 },
  questionHint:      { fontSize: 13, color: "#8a8a8a", margin: "0 0 10px" },
  chipsRow:          { display: "flex", flexWrap: "wrap" as const, gap: 8 },
  chip:              { padding: "7px 16px", fontSize: 13, fontWeight: 500, borderRadius: 999, cursor: "pointer", fontFamily: "inherit", transition: "all 0.12s ease", whiteSpace: "nowrap" as const },
  chipOtherInput:    { padding: "6px 14px", fontSize: 13, border: "1px solid #d4d2cc", borderRadius: 999, background: "#ffffff", outline: "none", fontFamily: "inherit", color: "#1a1a1a", minWidth: 100 },
  questionInput:     { width: "100%", padding: "10px 14px", fontSize: 14, border: "1px solid #d4d2cc", borderRadius: 10, background: "#ffffff", outline: "none", fontFamily: "inherit", color: "#1a1a1a", boxSizing: "border-box" as const },
  questionTextarea:  { width: "100%", padding: "10px 14px", fontSize: 14, border: "1px solid #d4d2cc", borderRadius: 10, background: "#ffffff", outline: "none", fontFamily: "inherit", color: "#1a1a1a", resize: "vertical" as const, lineHeight: 1.5, boxSizing: "border-box" as const },
  questionsFooter:   { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 48px", borderTop: "1px solid #e0ded8", background: "#f0efeb", flexShrink: 0 },
  continueBtn:       { padding: "10px 28px", fontSize: 14, fontWeight: 600, color: "#ffffff", border: "none", borderRadius: 10, fontFamily: "inherit", transition: "background 0.15s" },

  tweaksBar:         { display: "flex", alignItems: "center", gap: 4 },
  tweaksDivider:     { width: 1, height: 18, background: "#d4d2cc", margin: "0 4px", flexShrink: 0 },
  toggleTrack:       { width: 28, height: 16, borderRadius: 999, border: "none", cursor: "pointer", position: "relative" as const, padding: 0, transition: "background 0.2s", flexShrink: 0 },
  toggleThumb:       { position: "absolute" as const, top: 2, left: 2, width: 12, height: 12, borderRadius: "50%", background: "#ffffff", transition: "transform 0.2s", display: "block" },
  zoomBtn:           { width: 22, height: 22, display: "flex", alignItems: "center", justifyContent: "center", background: "none", border: "1px solid #d4d2cc", borderRadius: 5, cursor: "pointer", fontSize: 13, color: "#4a4a4a", fontFamily: "inherit", lineHeight: 1 },
}
